### PR TITLE
changed metric fetch to use pmid instead of name

### PR DESCRIPTION
**Pull request by hc000**
created cache of metric name and pmid values
initial call is made using name, subsequent calls are done via pmid

### CODE REVIEW

**Comment by spiermar** [comment]
There's a problem with that logic where new widgets would not get any data. That happens because of the `angular.isDefined(PMID[response])` check. After the first items are added to the cache, it would only request PMIDs that are already in the cache, and ignore new metrics.

I would also avoid creating a variable scoped at the whole service to hold the PMID cache. Probably a better place for this information would be the SimpleMetric class. Update could be done in the `getMetrics` callback in `DashboardService`, same as a `pushValues`. 

The `getMetricsValues` method already accepts PMIDs too, but nothing is being sent right now. To request using that method, it would be just a matter of creating two arrays instead of one on `getMetrics`, one with the metric names, for the ones without PMID, and another with the PMIDs.

Also, the `cachePMIDs` function is being called every time to update the whole cache, which might not be necessary.

**Comment by spiermar** [comment]
I'm involved with another issue now, but I can try to get something working for this later in the week.

**Comment by spiermar** [comment]
Just tested it locally and the requests are still using names instead of the PMIDs on #397aff1

`GET http://ip-100-66-39-152.ec2.internal:7402/pmapi/1084163488/_fetch?names=containers.cgroup,containers.name,kernel.all.load`

Is the same thing happening to you @hc000 ?

**Comment by hc000** [comment]
@spiermar: Weird, I'm not seeing that
screen shot 2016-08-22 at 9 30 20 am

**Comment by spiermar** [comment]
Same commit? `git checkout -b hc000-pmid origin/hc000-pmid`
That's strange. I'll debug it and see what I can find.

**Comment by hc000** [comment]
I just did a clean test, created new folder, pulled from github, checked out the hc000-pmid branch and got the same result as the screenshot. Did you have a different combination of widgets on startup then switched to that one? or were you using the default?

**Comment by spiermar** [comment]
Just that `kernel.all.load`. I'll try with some different widgets.

**Comment by spiermar** [comment]
Found a few problems, but figured it would be easier to just merge and fix-forward. Should be pushing some changes later this afternoon and bumping a minor version.

**Pull request merged**
