### PR TITLE
Typo on flame graph template location

### PR DESCRIPTION
**Pull request by matschaffer**
Btw, how exactly do you get a version of pmapi that answers to generic.systack ?

### CODE REVIEW

**Comment by matschaffer** [comment]
Ah, I see that #7 lists is as an enhancement. Seems like it's at least trying from looking at the chrome network tab. Just pcp doesn't know what to do with the request.

**Comment by spiermar** [comment]
Tks @matschaffer ! Yeah, that's why it's disabled by default. FlameGraph requires a custom PCP agent. We have it enabled internally, but it's not polished enough yet. Happy to share it if there's interest.

**Comment by matschaffer** [comment]
If it's not much trouble I'd love to try it. Building flame graphs by hand
isn't bad but point and click would be really nice.

2015年5月19日火曜日、Martin Spier<notifications@github.com>さんは書きました:

**Comment by spiermar** [comment]
We created a really (really) simple pmda to help a bit with that. Basically it just executes perf and the script to generate the flame graph, and outputs the SVG file to a public directory served by pmwebd. The Vector widget gets that SVG graph and places it into a widget. As I mentioned, really dirty and simple. We will probably have a D3 version of the flame graph in a couple weeks or so. Once that is done, I can start working on making the pmda output to json and draw the graph on Vector.

https://github.com/spiermar/flamegraph-pmda

Haven't tried building it outside of our environment, but technically it should work.

**Comment by matschaffer** [comment]
Sweet! I'll put it on the old backlog.

@spiermar as a side-note. How do you recommend running Vector? I noticed the angular app is ~2MB download. Do you serve it from a shared instance?

Seems like that could get some caching advantage over running it on every instance.

**Comment by spiermar** [comment]
Yes, we serve it from a shared instance. Not just caching, but it makes our lives easier when upgrading to a new version. Just need to update one host. :-)

**Pull request merged**
