### PR TITLE
Add support for the protocol to be specified against a context

### PR DESCRIPTION
**Pull request by JoshKeegan**
Adds support for the protocol that's used to communicate with the PCP Web API to be specified against each context.  

The user is given a drop-down when they go to add a new connection:
image

### CODE REVIEW

**Comment by jasonk000** [comment]
Thanks for the pr @JoshKeegan , looks good .. I'll do some local testing too

**Comment by jasonk000** [comment]
Thanks!

**Comment by jasonk000** [comment]
I just noticed @JoshKeegan that there is an empty box in the protocol dropdown, on first load:

image

If you're up for it - would you be able to make that consistent as well?

**Comment by JoshKeegan** [comment]
I can take a look. What browser was this in?

**Comment by jasonk000** [comment]
Firefox 66

**Comment by JoshKeegan** [comment]
@jasonk000 I'm unable to reproduce this (using FF 66.0.2, Windows 7 x64).  
Perhaps there's something being cached by your browser?

**Comment by jasonk000** [comment]
I believe you are correct. I'm no longer seeing the issue. Thanks!

**Pull request merged**
