### PR TITLE
Change project structure to match generator-angular-gulp format

### PR DESCRIPTION
**Pull request by meteorfox**
I understand this a very big refactor, related to issue #8 , but in my opinion is worth it, here'a few reasons why:
- Adds ability to minify and compress, reducing number of bytes transferred
- Concatenates all vendor JS into a vendor.js, all app scripts to app.js, and partials use templateCache, which reduces number of requests to the page
- Takes care of renaming built resources with hashes to help with browser cache invalidation
- Follows recommended structure by [generator-gulp-angular ](https://github.com/Swiip/generator-gulp-angular)
- Several new gulp tasks for browser live refreshes, and building 'prod' distribution with minified resources

### CODE REVIEW

**Comment by spiermar** [comment]
I'll have to manually merge this after the previous changes.

**Comment by meteorfox** [comment]
Don't merge yet.

Let me just rebase, and resolved the conflicts.

**Comment by spiermar** [comment]
Ok

**Comment by meteorfox** [comment]
I rebased the branch with master, and fixed merge conflicts. Just a reminder, this commit changes the project to have the structure and automation recommended by the Yeoman's generator-gulp-angular.

Here's docs for the different tasks included with gulp:
https://github.com/Swiip/generator-gulp-angular#use-gulp-tasks

and the project structure it follows:
https://github.com/Swiip/generator-gulp-angular#directory-structure

**Comment by spiermar** [comment]
Looks good. I'll merge and update the wiki and build jobs tomorrow. Still trying to figure out the best place to put the html templates.

**Comment by meteorfox** [comment]
It seems the styleguides out there recommend placing the template on the same directory where the directive that uses it is. That way related files are together.

[1] https://github.com/Swiip/generator-gulp-angular#directory-structure
[2] https://github.com/johnpapa/angular-styleguide#folders-by-feature-structure

**Comment by spiermar** [comment]
Merged. Will move a few things around and fix the eslint errors. ;-)

**Comment by meteorfox** [comment]
Awesome thanks! Note that it also runs jshint, but there are a lot of warnings.

Also, probably you know this, but to run the development server just use `gulp serve` and it will build/lint and automatically open a tab in your browser with Vector, it will also automatically refresh whenever you change a file.

If you want to locally run the 'production' version, with all the resources minified/concatenated/uglyfied. Simply just execute `gulp serve:dist`. It takes a few seconds because of the inject phase. 

Finally to just build a production version, just execute `gulp build`, and will create a directory named `dist/` with all the resources minified/concatenated/uglyfied inside it, and all that is left is drop it and serve it with Apache/NGINX.

To run unit tests: `gulp test`
To run e2e tests: `gulp protractor`

**Pull request merged**
