### PR TITLE
Project Structure

### PR DESCRIPTION
**Pull request by spiermar**
Breaking factories into app.metrics modules.

### CODE REVIEW

**Comment by spiermar** [comment]
@meteorfox @zanthrash @dylanjohnson feedback is appreciated :-)

**Comment by spiermar** [comment]
Working on data models right now.

**Comment by meteorfox** [comment]
LGTM :+1: 

As we break up this big files into multiple files, we also need to start thinking how can we concatenate them, and minify them as part of the 'build' step with gulp, so the browser doesn't issue that many requests.

**Comment by spiermar** [comment]
agreed @meteorfox ! we definitely need gulp tasks to concatenate, minify and compress files. I'm checking your PR and a few other options too. ;-)

**Pull request merged**
