### PR TITLE
PMCD target

### PR DESCRIPTION
**Pull request by spiermar**
It's working and I tried to keep the UI changes to a minimum. Let me know what you think @fche .
If it looks good, we can look into loading different defaults if Vector is being served by pmwebd, probably changing hostname to localhost and expanding the hostspec automatically.

### CODE REVIEW

**Comment by fche** [comment]
I like the + dropdown gui in this version, but miss the ability to set a pmwebd port number, the setting of the pmcd hostspec in $location.search(), and the actual remote-instance host-name lookup (pmcd.hostname query).  (Remember that the pmwebd connection string, and indeed the pmwebd-to-pmcd connection string, are all relative to their respective nodes.  They are not the final 'name' of the target host - just steps along the route to reach it.  Each step can be "localhost", esp. with some proxy/port number, and end up referring to a machine far away.)

**Comment by spiermar** [comment]
Ok, so I'm trying to visualize how this would be used since it's not a use case we have. Like Freddy Krueger, let's go by parts.
1. pmwebd port number configuration is easy to add, I just want to make sure this is a common use case, where people will actually have to change the port number on the fly. My assumption was always that people would generally run pmwebd in the same port across an organization, so a port configuration would just complicate things. But I might be wrong. Adding an override to the search bar might be an option too.
2. pmcd hostspec on $location.search(). Missed that one. Just added it on bb38044c7763887446987a13656da2e1c2bb3c2b .
3. The remote-instance host-name lookup. Can you send an example? Requests, etc..

**Comment by spiermar** [comment]
This part?

```
            // fetch hostname
            PMAPIService.getMetrics(data, ["pmcd.hostname"])
                .then(function (metrics) {
                    angular.forEach(metrics.values, function (values) {                    
                        angular.forEach(values.instances, function (pair) {
                            $rootScope.properties.hostname = metrics.values[0].instances[0].value;
                            $log.info("Hostname updated: " + $rootScope.properties.hostname);
                        });
                    });
                });
```

**Comment by spiermar** [comment]
I wasn't exactly sure how the hostname property was being used. After the "pmcd.hostname" request, the property was updated, but the only place where it was being used was to display "(disconnected)" or the pmcd hostname.

```
Hostname {{properties.context >= 0 ? properties.hostname : "(disconnected)"}}
```

Using the current input field, I have the checkmark to provide feedback to the user if context is available (connected) or not.

If I understood it correctly, the end goal is to get the pmcd hostname and show it somewhere, right?

**Comment by spiermar** [comment]
Ok. Displaying the hostname is simple. I'll probably add a label next to the hostspec input. Does that work for you?
About the port, I see a use case where Vector is distributed with pmwebd and the pmwebd port is changed. Now you would need to change the port on both pmwebd config and also on Vector's config. 
If that's the use case you have in mind, one solution would be to detect if pmwebd is serving Vector, and if it is, override the host and port configs to localhost and whatever port vector is being served from.

**Comment by spiermar** [comment]
Pushed the pmcd hostname change. 6063ac223a40964709479eca3f6f2589e79ebec1

**Comment by spiermar** [comment]
Think I've found a good solution for the pmwebd port number. I can parse the text in the hostname field and if it includes a port, I can parse it and update the port parameter.

**Comment by fche** [comment]
Your changes look really good now, thanks.  (If it were up to me, I'd probably still prefer to see the pmcd.hostname as the visible-by-default field up by Hostname:, and let the pmwebd host:port be a separate input, but it's not a huge deal.)

**Comment by spiermar** [comment]
It makes sense if you're serving Vector from pmwebd. We can change the order, or even hide the pmwebd hostname field if we detect it's being served by pmwebd. Creating an issue to track this.

**Pull request merged**
